Resolve using list instead of get
microsoft/vscode-azurefunctions pull request #3726
Opened 2023-06-23 19:15 UTC by alexweininger

Fixes #3723 

Making a HTTP request for each resource is really hurting performance. Ideally we can delay these requests until the user expands the resource or invokes a command on it, but for now I think this is the best solution.

The cache only valid for 3 seconds, long enough to make sure the entire batch of resolve calls can hit the cache. I didn't do anything fancy since I want to validate with the customer that this speeds things up. I figure we can make a util and share this across extensions later.

2023-06-24 00:01 UTC, nturinski approved these changes

2023-06-24 00:09 UTC, nturinski requested changes
Actually, you never actually clear the cache. I'm worried that if we delete a function app, the siteCache will still be in the map because we're doing a list, and then a for each over the returned sites list.

We could just save the array instead and delete that whenever we reset the cache? It might be easier to maintain, though that's not necessarily better than a map or anything.

2023-06-26 17:21 UTC, alexweininger commented
> Actually, you never actually clear the cache. I'm worried that if we delete a function app, the siteCache will still be in the map because we're doing a list, and then a for each over the returned sites list.

Good catche 😄 , it's probably a good idea to clear the cache.

I do want to note that technically delete would work OK since RGs will always re-list the resources and only resolve what it knows about. So having deleted things in the cache wouldn't cause issues for that particular case.

I do think it might cause issues at other times, so it's still a good idea.

2023-06-26 20:44 UTC, nturinski approved these changes

2023-06-30 20:06 UTC, alexweininger commented
Since the release is delayed maybe we merge this and do another round of testing.

2023-06-30 20:09 UTC, merged